# Generated by Django 3.1.5 on 2021-01-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
